services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: httpsms
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbusername
    volumes:
      # Criamos um nome novo (v2) para forçar a criação de um disco limpo
      - postgres_data_v2:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      # Novo volume para o Redis também, só por precaução
      - redis_data_v2:/var/lib/redis
    ports:
      - "6379:6379"
    restart: on-failure

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started # Agora ele só exige que o banco inicie, sem testes chatos
      redis:
        condition: service_started
    env_file:
      - ./.env
    restart: on-failure # Se a API ligar antes do banco estar 100% pronto, ela reinicia sozinha

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    restart: on-failure

volumes:
  # Declarando os novos volumes limpos
  redis_data_v2:
  postgres_data_v2:
