services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: httpsms
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbusername
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data_v2:/var/lib/redis
    ports:
      - "6379:6379"
    restart: on-failure

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./.env
    restart: on-failure

  web:
    build:
      context: ./web
    ports:
      - "3005:3000"
    depends_on:
      api:
        condition: service_started
    # A CORREÇÃO ESTÁ AQUI: Agora o Web também lê as variáveis do Easypanel
    env_file:
      - ./.env
    restart: on-failure

volumes:
  redis_data_v2:
  postgres_data_v2:
